- public/skcm_tcga.tar.gz
Remove '---' from Validation_Status and Validation_Method with:
```
cat data_mutations_extended.txt | awk -F '\t' -v OFS='\t' '{ if ($25 == "---") {$25 = ""}; if ($29 == "---") {$29 = ""}; print }' > data_mutations_extended_new.txt
mv data_mutations_extended_new.txt data_mutations_extended.txt
```
> Fix data_mutations_extended.txt in skcm_tcga

- public/msk_impact_2017.tar.gz
> Adding msk_impact_2017

- public/lgg_ucsf_2014.tar.gz
> Updates to lgg_ucsf_2014

- public/brca_tcga.tar.gz
- public/coadread_tcga.tar.gz
- public/ov_tcga.tar.gz
Attempts to resolve #32. Mass spec files newly generated by @pambot. Zscores for mass spec generated by me.
> Updated mass spec and z scores

- public/hcc_inserm_fr_2015.tar.gz
Adding new public study hcc_inserm_fr_2015
> Adding study hcc_inserm_fr_2015

- public/dlbc_tcga.tar.gz
- public/ov_tcga.tar.gz
TCGA-DLBC updates:
TCGA-OV updates:
* data_bcr_clinical_data_sample.txt
* data_mRNA_median_Zscores.txt
* data_rppa.txt
* data_rppa_Zscores.txt
* data_protein_quanitification.txt
* data_protein_quanitification_Zscores.txt
* cases_all.txt
* cases_rppa.txt
> TCGA-DLBC and TCGA-OV data updates

- public/acc_tcga.tar.gz
> TCGA-ACC updates

- public/brca_tcga.tar.gz
Files updated:
* cases_protein_quantification.txt
* data_protein_quantification.txt
* data_protein_quantification_Zscores.txt
* data_mRNA_median_Zscores.txt
> TCGA-BRCA Updates

- public/coadread_tcga.tar.gz
TCGA-COADREAD updates:
* removed hidden case lists
* data_mRNA_median_Zscores.txt
* cases_all.txt
* cases_protein_quanitification.txt
> TCGA-COADREAD updates:

- public/meso_tcga.tar.gz
> TCGA-MESO updates

- public/pcpg_tcga.tar.gz
- public/thym_tcga.tar.gz
- public/uvm_tcga.tar.gz
TCGA-PCPG updates:
TCGA-THYM updates:
TCGA-UVM updates:
> TCGA-PCPG, THYM, UVM updates

- public/cesc_tcga.tar.gz
> TCGA-CESC updates

- public/luad_tcga.tar.gz
- public/lusc_tcga.tar.gz
- public/paad_tcga.tar.gz
- public/sarc_tcga.tar.gz
TCGA-LUAD updates:
* data_mRNA_median_Zscores.txt
* data_rppa.txt
* data_rppa_Zscores.txt
TCGA-LUSC updates:
* data_rppa.txt
* data_rppa_Zscores.txt
TCGA-PAAD updates:
* data_rppa.txt
* data_rppa_Zscores.txt
TCGA-SARC updates:
* …
> TCGA-LUAD, LUSC, PAAD, SARC updates

- seedDB/README.md
- seedDB/Update-Seed-Database.md
- seedDB/seed-cbioportal_hg19_v2.3.1.sql.gz
- seedDB/seed-cbioportal_hg19_v2.3.1_only-pdb.sql.gz
- seedDB/seed-cbioportal_hg19_v2.4.0.sql.gz
- Update seed to 2.4.0
- Remove PDB part
- Update documentation
> Update seed to 2.4.0

- .circleci/config.yml
related to issue reported here https://discuss.circleci.com/t/config-file-error/21474/16
to get rid of these errors in Circle CI:
> small fix to .yaml to remove trailing tabs

- public/paad_tcga/data_mutsig.txt
- public/paad_tcga/meta_mutsig.txt
resolving issue: https://github.com/cBioPortal/datahub/issues/278
> removed mutsig from paad_tcga

- public/chol_tcga_pan_can_atlas_2018/meta_study.txt
- public/coad_tcga_pan_can_atlas_2018/meta_study.txt
to solve issue:https://github.com/cBioPortal/datahub/issues/317
> swapped short name for chol and coad tcga pancan

- public/egc_msk_2017/meta_study.txt
> Updated meta study name

- public/egc_msk_2017/data_clinical_sample.txt
> update cancer type case error in egc_msk_2017

- public/breast_msk_2018/data_clinical_sample.txt
> Updated clinical headers

- public/angs_project_painter_2018/data_clinical_patient.txt
- public/angs_project_painter_2018/data_clinical_sample.txt
> Updated clinical data

- public/ccrcc_irc_2014/data_clinical_sample.txt
Fix issue https://github.com/cBioPortal/datahub/issues/313
- ccrcc_irc_2014
Triage Instance: 
http://triage.cbioportal.mskcc.org/study?id=ccrcc_irc_2014#summary
> filled back the values for FUHRMAN_GRADE from original paper

- public/sarc_mskcc/meta_mRNA_outliers.txt
added meta data for mRNA outlier expression
> sarc_mskcc: fixing importing errors

- .circleci/validate_all_studies.sh
Fix validate all studies test.
> Fix validate all studies test

- public/brca_mbcproject_wagle_2017/data_clinical_patient.txt
- public/brca_mbcproject_wagle_2017/data_clinical_sample.txt
> Updated clinical data for MBC cohort

- public/nepc_wcm_2016/data_expression_median.txt
- public/nepc_wcm_2016/meta_expression_median.txt
> Updated expression data for nepc

- public/brca_metabric/data_gene_matrix.txt
> Updated gene panel matrix for CNA

- public/brca_mbcproject_wagle_2017/meta_study.txt
> Updated meta study

- public/um_qimr_2016/case_lists/cases_all.txt
- public/um_qimr_2016/case_lists/cases_sequenced.txt
- public/um_qimr_2016/case_lists/cases_wes.txt
- public/um_qimr_2016/case_lists/cases_wgs.txt
- public/um_qimr_2016/data_SV.txt
- public/um_qimr_2016/data_clinical_patient.txt
- public/um_qimr_2016/data_clinical_sample.txt
- public/um_qimr_2016/data_fusions.txt
- public/um_qimr_2016/data_mutations_extended.txt
- public/um_qimr_2016/data_mutations_mskcc.txt
- public/um_qimr_2016/meta_clinical_patient.txt
- public/um_qimr_2016/meta_clinical_sample.txt
- public/um_qimr_2016/meta_fusions.txt
- public/um_qimr_2016/meta_mutations_extended.txt
- public/um_qimr_2016/meta_study.txt
- public/vsc_cuk_2018/case_lists/cases_all.txt
- public/vsc_cuk_2018/case_lists/cases_sequenced.txt
- public/vsc_cuk_2018/data_clinical_patient.txt
- public/vsc_cuk_2018/data_clinical_sample.txt
- public/vsc_cuk_2018/data_mutations_extended.txt
- public/vsc_cuk_2018/data_mutations_mskcc.txt
- public/vsc_cuk_2018/meta_clinical_patient.txt
- public/vsc_cuk_2018/meta_clinical_sample.txt
- public/vsc_cuk_2018/meta_mutations_extended.txt
- public/vsc_cuk_2018/meta_study.txt
> Add new studies

- public/all_stjude_2015/data_mutations_extended copy.txt
- public/all_stjude_2015/data_mutations_extended.txt
- public/all_stjude_2015/data_mutations_mskcc.txt
reannotated, fixed file format (change to UTF_8)
> fixed MAF issue in all_stjude_2015 

- public/brca_metabric/data_expression_median.txt
- public/nepc_wcm_2016/data_RNA_Seq_expression_median.txt
- nepc_wcm_2016
- brca_metabric
> replaced NA with space in RNA seq exp files

- public/coadread_tcga_pub/data_clinical_patient.txt
- public/coadread_tcga_pub/data_clinical_sample.txt
Fix issue https://github.com/cBioPortal/datahub/issues/453
> fix clinical data issue: duplicate samples, format

- public/glioma_msk_2018/data_clinical_sample.txt
- public/glioma_msk_2018/data_timeline.txt
- public/glioma_msk_2018/meta_timeline.txt
> Added timeline Data

- public/glioma_msk_2018/meta_study.txt
> Updated groups

- public/tmb_mskcc_2018/data_mutations_extended.txt
- public/tmb_mskcc_2018/data_mutations_mskcc.txt
adjusted shifted columns in msk MAF (sample_ID); run cleanup script o…
> tmb_mskcc_2018: fix MAF importing error

- public/coadread_dfci_2016/data_mutations_extended.txt
- public/coadread_dfci_2016/data_mutations_mskcc.txt
> Added missing mutations to coadread_dfci_2016

- public/skcm_tcga/data_RNA_Seq_v2_mRNA_median_Zscores.txt
Fix # https://github.com/cBioPortal/datahub/issues/534
- skcm_tcga
> regenerated zscore for skcm_tcga

- public/tet_nci_2014/meta_mutations_extended.txt
- public/tet_nci_2014/meta_study.txt
> QC tet_nci_2014 

- public/uccc_nih_2017/meta_mutations_extended.txt
> QC uccc_nih_2017

- .circleci/install_dependencies.sh
- public/stad_utokyo/data_clinical_sample.txt
- public/stad_utokyo/meta_mutations_extended.txt
- public/stad_utokyo/meta_study.txt
update meta study/mut, update clin attr type
> QC stad_utokyo

- public/stad_tcga_pub/meta_mutations_extended.txt
- public/stad_tcga_pub/meta_study.txt
Fixing https://github.com/cBioPortal/datahub/issues/623
> stad_tcga_pub: update meta study&mut with matched normal and profile information

- public/acyc_mgh_2016/data_clinical_sample.txt
> Added sample class

- public/prad_fhcrc/data_mRNA_median_Zscores.txt
- public/prad_fhcrc/meta_mRNA_median_Zscores.txt
> prad_fhcrc: Added z-score file

- public/thca_tcga_pub/data_fusions.txt
Sample removed: TCGA-BJ-A0ZF-01
> thca_tcga_pub: Removed extra sample not in publication from fusion file

- .circleci/check_all_studies_imported.py
- .circleci/config.yml
Make sure all studies on datahub are imported in cbioportal.org and vice
versa: the studies on cbioportal.org are on datahub
> Add daily run circleci to see if studies imported

- .circleci/config.yml
The script does not have a shebang set so call the script with python directly
> Fix circleci import test

- public/skcm_tcga/data_RNA_Seq_v2_mRNA_median_Zscores.txt
> skcm_tcga: recalculated RNA Seq zscores to restore missing genes

- .circleci/config.yml
Fixes issue: https://github.com/cBioPortal/cbioportal/issues/6586
> Fix circleci default 10 minute no-output timeout issue

- public/paad_qcmg_uq_2016/meta_RNA_Seq_v2_expression_median.txt
> paad_qcmg_uq_2016: fixed issue #830

- public/brca_tcga_pub2015/meta_linear_CNA.txt
> brca_tcga_pub2015: fixed wrong profile name

- public/mel_ucla_2016/case_lists/cases_RNA_Seq_mRNA.txt
- public/mel_ucla_2016/case_lists/cases_all.txt
- public/mel_ucla_2016/case_lists/cases_cna.txt
- public/mel_ucla_2016/case_lists/cases_cnaseq.txt
- public/mel_ucla_2016/case_lists/cases_complete.txt
- public/mel_ucla_2016/case_lists/cases_sequenced.txt
- public/mel_ucla_2016/data_CNA.txt
- public/mel_ucla_2016/data_RNA_Seq_expression_median.txt
- public/mel_ucla_2016/data_RNA_Seq_mRNA_median_Zscores.txt
- public/mel_ucla_2016/data_clinical_patient.txt
- public/mel_ucla_2016/data_clinical_sample.txt
- public/mel_ucla_2016/data_cna_hg19.seg
- public/mel_ucla_2016/data_gistic_genes_amp.txt
- public/mel_ucla_2016/data_gistic_genes_del.txt
- public/mel_ucla_2016/data_mutations_extended.txt
- public/mel_ucla_2016/data_mutations_mskcc.txt
- public/mel_ucla_2016/meta_CNA.txt
- public/mel_ucla_2016/meta_RNA_Seq_expression_median.txt
- public/mel_ucla_2016/meta_RNA_Seq_mRNA_median_Zscores.txt
- public/mel_ucla_2016/meta_clinical_patient.txt
- public/mel_ucla_2016/meta_clinical_sample.txt
- public/mel_ucla_2016/meta_cna_hg19_seg.txt
- public/mel_ucla_2016/meta_gistic_genes_amp.txt
- public/mel_ucla_2016/meta_gistic_genes_del.txt
- public/mel_ucla_2016/meta_mutations_extended.txt
- public/mel_ucla_2016/meta_study.txt
Fix #736 
Triage Testing Instance: https://triage.cbioportal.mskcc.org/study/summary?id=mel_ucla_2016
> new study: mel_ucla_2016

- public/blca_plasmacytoid_mskcc_2016/data_gene_matrix.txt
- public/blca_plasmacytoid_mskcc_2016/meta_CNA.txt
- public/blca_plasmacytoid_mskcc_2016/meta_gene_matrix.txt
- blca_plasmacytoid_mskcc_2016_gene_matrix
> blca_plasmacytoid_mskcc_2016: added gene panel matrix

- public/hcc_mskimpact_2018/data_gene_matrix.txt
- public/hcc_mskimpact_2018/meta_gene_matrix.txt
hcc_mskimpact_2018: added gene matrix
- hcc_mskimpact_2018
> hcc_mskimpact_2018: added gene matrix

- reference_data/gene_panels/data_gene_panel_prad_mskcc_1.txt
- reference_data/gene_panels/data_gene_panel_prad_mskcc_2.txt
Introduce two new panels by prad_mskcc
Publication link:
https://www.sciencedirect.com/science/article/pii/S1535610810002382?via%3Dihub#sec5
Study Link:
https://www.cbioportal.org/study/summary?id=prad_mskcc#summary
> added 2 new panels (from prad_mskcc)

- public/summit_2018/data_gene_matrix.txt
- public/summit_2018/meta_gene_matrix.txt
> summit_2018: added gene matrix

- public/blca_tcga_pub/meta_mutations_extended.txt
- public/blca_tcga_pub/meta_study.txt
- public/blca_tcga_pub_2017/meta_mutations_extended.txt
- public/blca_tcga_pub_2017/meta_study.txt
- public/utuc_mskcc_2015/data_gene_matrix.txt
- public/utuc_mskcc_2015/meta_gene_matrix.txt
- utuc_mskcc_2015
- blca_tcga_pub
- blca_tcga_pub_2017
> Gene panel info update for utuc_mskcc_2015, blca_tcga_pub, blca_tcga_pub_2017

- reference_data/gene_panels/data_gene_panel_archer_heme.txt
- reference_data/gene_panels/data_gene_panel_archer_solid.txt
- reference_data/gene_panels/data_gene_panel_heme400.txt
- reference_data/gene_panels/data_gene_panel_heme_hotspot.txt
- reference_data/gene_panels/data_gene_panel_rdtb49.txt
- reference_data/gene_panels/data_gene_panel_rdts30.txt
Added gene panels (archer, raindance)
> added gene panels

- public/ccle_broad_2019/data_CNA.txt
> fixed CNA file

- public/msk_impact_2017/data_SV.txt
> Added SV file from 11/3

- public/pediatric_dkfz_2017/data_clinical_sample.txt
Fix #902
- pediatric_dkfz_2017
> pediatric_dkfz_2017: fixed cancer type, added tumor details

- public/coad_cptac_2019/data_RNA_Seq_v2_expression_RSEM_UQ_Log2_Zscores.txt
- public/coad_cptac_2019/data_miRNA_median_Zscores.txt
- public/coad_cptac_2019/data_protein_quantification_Zscores.txt
- public/coad_cptac_2019/meta_RNA_Seq_v2_expression_RSEM_UQ_Log2.txt
- public/coad_cptac_2019/meta_RNA_Seq_v2_expression_RSEM_UQ_Log2_Zscores.txt
- public/coad_cptac_2019/meta_miRNA_median_Zscores.txt
- public/coad_cptac_2019/meta_protein_quantification_Zscores.txt
Reverts cBioPortal/datahub#812
> Revert "coad_cptac_2019: Added Zscore files"

- public/brca_tcga/data_RNA_Seq_v2_mRNA_median_Zscores.txt
- public/ov_tcga/data_RNA_Seq_v2_mRNA_median_Zscores.txt
Reverts cBioPortal/datahub#813
> Revert "ov_tcga & brca_tcga: Recalculated RNA_Seq zscores"

- public/lcll_broad_2013/data_clinical_sample.txt
> Icll_broad_2013: Fixed cancer type

- reference_data/gene_panels/data_gene_panel_cmo_hemepact_v3.txt
> added new gene panel hemepact_v3

- public/lymphoma_cellline_msk_2020/data_clinical_sample.txt
> lymphoma_cellline_msk_2020: update tumor site in clinical

- public/utuc_pdx_msk_2019/meta_mutations_extended.txt
- public/utuc_pdx_msk_2019/meta_study.txt
> Updated study description: utuc_pdx_msk_2019

- public/lymphoma_cellline_msk_2020/Readme.txt
- public/utuc_msk_2019/Readme.txt
- public/utuc_pdx_msk_2019/Readme.txt
lymphoma_cellline_msk_2020/Readme.txt
utuc_msk_2019/Readme.txt
utuc_pdx_msk_2019/Readme.txt
> added missing gene panel info readme

- public/msk_impact_2017/data_mutational_signature_confidence.txt
- public/msk_impact_2017/data_mutational_signature_contribution.txt
- public/msk_impact_2017/meta_mutational_signature_confidence.txt
- public/msk_impact_2017/meta_mutational_signature_contribution.txt
Added data_mutational_signature_contribution.txt and updated data_mutational_signature_confidence.txt data.
> msk_impact_2017: added mutational_signature data

- public/utuc_pdx_msk_2019/meta_study.txt
> utuc_pdx_msk_2019: updated study name

- public/utuc_msk_2019/data_clinical_sample.txt
- public/utuc_pdx_msk_2019/data_clinical_sample.txt
Added Collaboration IDs to studies
- utuc_msk_2019
- utuc_pdx_msk_2019
> Added Collab IDs to utuc_pdx_msk_2019 and utuc_msk_2019

- public/gbm_columbia_2019/data_clinical_patient.txt
> gbm_columbia_2019: updated OS PD1 related attributes ID

- public/prad_cdk12_mskcc_2020/data_clinical_patient.txt
- public/prad_cdk12_mskcc_2020/data_clinical_sample.txt
- public/prad_cdk12_mskcc_2020/meta_study.txt
> Updated meta study and clin files

- public/all_stjude_2013/meta_study.txt
- public/hnc_mskcc_2016/meta_study.txt
> Fixed tumor types

- public/pediatric_dkfz_2017/data_mutations_extended.txt
- public/pediatric_dkfz_2017/data_mutations_mskcc.txt
- public/prad_mpcproject_2018/prad_mpcproject_2018.tar.gz
- contact: M.Zapatka@dkfz-heidelberg.de
- resource used to retrieving correct allele: 
https://pecan.stjude.cloud/proteinpaint/study/dkfz-ppc
Also fixed some `NA` values in the chromosome column.
> pediatric_dkfz_2017: fixed the un-annotated rows

- public/crc_msk_2017/data_mutations_extended.txt
- public/crc_msk_2017/data_mutations_mskcc.txt
- public/mcl_idibips_2013/data_mutations_extended.txt
- public/mcl_idibips_2013/data_mutations_mskcc.txt
- public/pact_jhu_2011/data_clinical_sample.txt
- public/pact_jhu_2011/data_mutations_extended.txt
- public/pact_jhu_2011/data_mutations_mskcc.txt
1. pact_jhu_2011 - 1 Mutated Event
2. mcl_idibips_2013 - 290 Mutated Events
3. crc_msk_2017 - 1 Mutated Event
```
select gp.stable_id
from mutation_event me, mutation m, genetic_profile gp 
where me.mutation_event_id=m.mutation_event_id and m.genetic_profile_id=gp.genetic_profile_id 
and protein_change='mutated' 
and gp.stable_id LIKE "%stes_tcga_pub%"
```
> Fixed mutated issue:Uniprot and MSK MAF

- public/mds_mskcc_2020/data_clinical_sample.txt
- public/mds_mskcc_2020/data_mutations_extended.txt
- public/mds_mskcc_2020/data_mutations_mskcc.txt
- updated 'NA' values into 'UNKNOWN' in `mutation_status` to get the right count
- update `matched normal` values in clinical files
- added MSK isoform MAF
> MDS_MSKCC_2020 update

- public/ccle_broad_2019/data_clinical_sample.txt
> Fixed the typo in clinical file

- public/prad_mich/case_lists/cases_mRNA.txt
> prad_mich: removed mRNA case list

- public/bfn_duke_nus_2015/data_clinical_patient.txt
- public/brca_bccrc/data_clinical_patient.txt
- public/brca_igr_2015/data_clinical_patient.txt
- public/prad_broad/data_clinical_patient.txt
- public/prad_broad_2013/data_clinical_patient.txt
1. bfn_duke_nus_2015
2. brca_bccrc
3. brca_igr_2015
4. prad_broad
5. prad_broad_2013
> Normalize Sex/gender

- public/msk_ch_2020/meta_study.txt
> msk_ch_2020: added citation

- public/cellline_ccle_broad/data_clinical_sample.txt
> Celline_ccle_broad : Updated Cancer types/Oncotree codes

- public/wt_stjude_2017/meta_study.txt
> wt_stjude_2017: Updated pmid and citation

- public/ihch_msk_2021/data_clinical_patient.txt
> clinical fix:ihch_msk_2021

- public/ihch_msk_2021/data_clinical_patient.txt
> Updated patient id's : ihch_msk_2021

- public/cscc_ucsf_2021/meta_study.txt
> cscc_ucsf_2021: add citation

- public/pan_origimed_2020/data_CNA.txt
Updated CNA data received from investigators.
> pan_origimed: update CNA data

- public/acyc_fmi_2014/data_mutations.txt
importing error: wrong unicode for data_mutations.txt
> acyc_fmi_2014: fixed unicode

- public/gbm_cptac_2021/data_acetylprotein_quantification.txt
- public/gbm_cptac_2021/data_phosphoprotein_quantification.txt
- public/gbm_cptac_2021/meta_acetylprotein_quantification.txt
- public/gbm_cptac_2021/meta_phosphoprotein_quantification.txt
> Gbm cptac update

- public/angs_painter_2020/data_clinical_patient.txt
- public/angs_painter_2020/data_clinical_sample.txt
Fix # 1562.
- angs_painter_2020.
> angs_painter_2020: Fileformat error

- public/skcm_tcga_pan_can_atlas_2018/data_mutations.txt
Fix #1594 .
- skcm_tcga_pan_can_atlas_2018.
> skcm_tcga_pan_can_atlas_2018:update MAF

- public/breast_ink4_msk_2021/meta_study.txt
Added citation for breast_ink4_msk_2021 study
> Add citation

- public/rectal_msk_2022/data_clinical_sample.txt
- public/rectal_msk_2022/data_cna.txt
- public/rectal_msk_2022/data_fusions.txt
- public/rectal_msk_2022/meta_fusions.txt
- public/rectal_msk_2022/meta_study.txt
https://github.com/knowledgesystems/curation-scrum/issues/1298
> rectal_msk_2022: fix data

- seedDB/README.md
Fix typo in the seedDB version number
> Update README.md - Fix typo

- public/lgsoc_mapk_msk_2022/meta_study.txt
> lgsoc_mapk_msk_2022: add citation

- public/brca_mbcproject_2022/data_sv.txt
- public/lung_nci_2022/data_sv.txt
- public/msk_impact_2017/data_sv.txt
- public/prad_su2c_2019/data_sv.txt
- public/um_qimr_2016/data_sv.txt
- brca_mbcproject_2022
- lung_nci_2022
- msk_impact_2017
- prad_su2c_2019
- um_qimr_2016
> SV validation error fix

- public/acc_2019/meta_study.txt
> Update cancer type acc-->acyc

- .circleci/config.yml
- .circleci/validate_changed_studies.sh
This improves the performance by doing these:
- Use `large` resource
- Enable parallelism (3 parallel instances)
- Separate the all-in-one validation command into individual test commands (one for each study)
> Circleci performance improvement

- public/sarcoma_mskcc_2022/meta_study.txt
> sarcoma_mskcc_2022: Add citation

- public/nsclc_ctdx_msk_2022/meta_study.txt
> nsclc_ctdx_msk_2022: added citation

- public/acc_2019/data_sv.txt
- public/egc_msk_tp53_ccr_2022/data_sv.txt
- public/lung_msk_mind_2020/data_sv.txt
- public/nsclc_pd1_msk_2018/data_clinical_sample.txt
- public/prad_mskcc/ignore_meta_mutsig.txt
- acc_2019
- egc_msk_tp53_ccr_2022
- lung_msk_mind_2020
- nsclc_pd1_msk_2018
- prad_mskcc
> Failed docker import 

- public/brca_mbcproject_2022/meta_mrna_seq_v2_rsem_zscores_ref_all_samples.txt
> Fixed typo in meta expression file

- public/nst_nfosi_ntap/meta_study.txt
Relates to #1734, minor description changes. 
- nst_nfosi_ntap
> Minor description changes

- public/nst_nfosi_ntap/meta_study.txt
Relates to https://github.com/cBioPortal/datahub/issues/1734. There is divergence in the variants identified in this submission compared to variants reported in the original publication. This is probably due to the differences in the details of reprocessing parameters. So I added a sentence to clarify the major differences in processing parameters.
- nst_nfosi_ntap
> Edit study description

- public/nst_nfosi_ntap/meta_study.txt
Related to #1734. Added a bit more language in the description to avoid code jargon
- nst_nfosi_ntap
> simplified description to avoid code jargon

- public/rectal_msk_2022/data_clinical_patient.txt
- public/rectal_msk_2022/data_clinical_sample.txt
- public/rectal_msk_2022/data_mutations.txt
> Add WES MAF

- public/ucec_ccr_cfdna_msk_2022/data_mutations.txt
Fix #1781 
- ucec_ccr_cfdna_msk_2022
> re-annotate MAF

- public/aml_ohsu_2022/data_clinical_sample.txt
- public/coad_silu_2022/data_clinical_sample.txt
to aml_ohsu_2022 and coad_silu_2022 studies
> add TMB scores

- public/mds_iwg_2022/data_mutations.txt
> mds_iwg_2022: re-annoted MAF

- public/lusc_cptac_2021/data_mutations.txt
> lusc_cptac_2022 :Re-annotated MAF

- README.md
> fix datasets page link

- public/bladder_msk_2023/meta_study.txt
- public/blca_bcan_hcrn_2022/meta_study.txt
- public/soft_tissue_msk_2023/meta_study.txt
Added PMIDs to:
- bladder_msk_2023
- blca_bcan_hcrn_2022
- soft_tissue_msk_2023
> Link PMIDs to studies

- public/brca_tcga/data_clinical_patient.txt
Currently shows DFS t0 as initial treatment but should be initial diagnosis.
> brca_tcga: update DFS description

- public/bm_nsclc_mskcc_2023/meta_study.txt
> study name update : bm_nsclc_mskcc_2023

- public/egc_trap_ccr_msk_2023/data_clinical_patient.txt
- public/egc_trap_ccr_msk_2023/meta_study.txt
- https://triage.cbioportal.mskcc.org/study/summary?id=ucec_ancestry_cds_msk_2023 
- https://triage.cbioportal.mskcc.org/study/summary?id=egc_trap_ccr_msk_2023
> Public release review

- public/crc_msk_2017/data_gene_panel_matrix.txt
Added CNA panel to gene matrix file.
> crc_msk_2017: add cna panel to gene matrix

- public/coadread_tcga_pan_can_atlas_2018/data_clinical_supp_hypoxia.txt
Added clinical attribute descriptions to Hypoxia data.
> coadread Pancan: Add meta clinical descriptions to supp file

- public/brca_metabric/meta_mrna_illumina_microarray.txt
- public/brca_metabric/meta_mrna_illumina_microarray_zscores_ref_diploid_samples.txt
Clarified the log intensity in the study is equivalent to log2 intensity.
> brca_metabric: update profile description

- public/msk_spectrum_tme_2022/meta_absolute_counts.txt
- public/msk_spectrum_tme_2022/meta_cell_cycle_counts.txt
- public/msk_spectrum_tme_2022/meta_cell_cycle_fraction.txt
- public/msk_spectrum_tme_2022/meta_relative_fraction.txt
update cell cycle and cell type profile names
> msk_spectrum: update cell cycle and cell type profile names

- public/coadread_tcga_pan_can_atlas_2018/data_clinical_supp_hypoxia.txt
-coadread_tcga_pan_can_atlas_2018
> Update hypoxia supp header- coadread_tcga_pan_can_atlas_2018

- .circleci/check_all_studies_imported.py
Fix https://github.com/cBioPortal/datahub/issues/2057.
/cc @inodb
> Update import checker to include GDC studies

- public/hnsc_tcga/data_clinical_patient.txt
> Updated the values of patient smoking history category

- .circleci/install_dependencies.sh
- .circleci/requirements.txt
git actions fails to identify the requests version 2.32.0
> Update requests version

- .circleci/requirements.txt
- public/egc_msk_2023/data_clinical_sample.txt
- public/mbn_sfu_2023/data_RNA_Seq_v2_mRNA_median_Zscores.txt
Fixed validation issues in:
- egc_msk_2023
- mbn_sfu_2023
> Fix validation issues

- public/all_phase2_target_2018_pub/meta_methylation_hm27.txt
> Update Methylation assay name- all_phase2_target_2018_pub

- public/msk_ch_2023/meta_mutations.txt
> Update the sequncing platform

- public/coadread_tcga_pan_can_atlas_2018/data_sv.txt
- public/egc_msk_2017/data_sv.txt
- public/egc_mskcc_2020/data_sv.txt
- public/ihch_msk_2021/data_sv.txt
- public/mel_mskimpact_2020/data_sv.txt
- public/ov_tcga_pan_can_atlas_2018/data_sv.txt
- egc_mskcc_2020
- ov_tcga_pan_can_atlas_2018
- coadread_tcga_pan_can_atlas_2018
- mel_mskimpact_2020
- egc_msk_2017
- ihch_msk_2021
> Added SV_status

- public/msk_chord_2024/meta_study.txt
- Updated study name and description.
> msk_chord_2024: update meta data description

- public/msk_chord_2024/data_clinical_patient.txt
- public/msk_chord_2024/data_clinical_sample.txt
- public/msk_chord_2024/data_cna.txt
- public/msk_chord_2024/data_sv.txt
> msk_chord_2024: fix validation issues

- public/msk_chord_2024/data_timeline_ca_15-3_labs.txt
- public/msk_chord_2024/data_timeline_ca_19-9_labs.txt
- public/msk_chord_2024/data_timeline_cea_labs.txt
- public/msk_chord_2024/data_timeline_psa_labs.txt
- public/msk_chord_2024/data_timeline_treatment.txt
- public/msk_chord_2024/data_timeline_tumor_markers.txt
- public/msk_chord_2024/meta_timeline_ca_15-3_labs.txt
- public/msk_chord_2024/meta_timeline_ca_19-9_labs.txt
- public/msk_chord_2024/meta_timeline_cea_labs.txt
- public/msk_chord_2024/meta_timeline_psa_labs.txt
Describe changes proposed in this pull request:
- msk_chord_2024
> lab test updates

- public/msk_chord_2024/data_clinical_sample.txt
Describe changes proposed in this pull request:
- msk_chord_2024
> MSK CHORD: Added TMB scores

- public/braf_msk_archer_2024/meta_study.txt
- public/braf_msk_impact_2024/meta_study.txt
Linked `braf_msk_archer_2024` and `braf_msk_impact_2024` as these come from the same paper.
> Update study description

- public/thyroid_gatci_2024/data_cna.txt
> Thyroid_gatci_2024 CNA update

- .circleci/validate_all_studies.sh
I've made a quick fix to see whether the validation test is fixed
> Quick fix validation test

- public/ovary_geomx_gray_foundation_2024/meta_study.txt
It's >400 ROIs, but only 34/35 cases
> Fix geomx description
