public/ucs_tcga.tar.gz
The ucs_tcga maf was missing some values for ref/tumor seq allele.
@jjgao @n1zea144
=> Fix for ucs_tcga maf

public/brca_tcga.tar.gz, public/coadread_tcga.tar.gz, public/ov_tcga.tar.gz
Fixes issues in #32 for brca, coadread, and ov TCGA studies.
=> Mass spec fixes

.circleci/run_tests.sh
With this change, any match to case_list*, caselist* will be seen as a potential case list dir.
In fact, only case_lists is currently recognized by the validation script. This change
ensures the validation is done only by the validation script which can now choose to 
give errors if appropriate (or become more flexible regarding the case list folder
name in the future).
=> Added heuristic to better recognize case lists dir

seedDB/README.md, seedDB/Update-Seed-Database.md, seedDB/seed-cbioportal_hg19_v2.4.0.sql.gz, seedDB/seed-cbioportal_hg19_v2.6.0.sql.gz
- Update database schema to 2.6.0
- Load MSigDB 6.1 gene sets in seed
- Load gene set hierarchy data in seed
- Update documentation
- Update genes (April 2018 from NCBI)
- Update gene lengths (Gencode Release 27)
Genes: 59976
Gene aliases: 66134
Pfam graphics: 21361
Info: DB_SCHEMA_VERSION: 2.4.0; GENESET_VERSION: null
Genes: 60070
Gene aliases: 66840
Gene sets: 17786
Pfam graphics: 21361
Info: DB_SCHEMA_VERSION: 2.6.0; GENESET_VERSION: msigdb_6.1
=> Update seed database to 2.6.0

README.md
To avoid users thinking this is the "latest" snapshot.
=> Added snapshot date to database snapshot link

.circleci/run_tests.sh
Setting the `--strict_mutation_checks` means `True`, so the extra value was not needed.
=> fixed strict_mutation_checks parameter

.circleci/run_tests.sh
Use seed database info for validation of studies.
The seed contains the genes, aliases and cancer types used for new cBio instances, so we have to make sure the studies on datahub validate using those definitions. We will have to add new cancer types from OncoTree to the outdated `type_of_cancer` table in the seed database.
=> Use seed database info for validation of studies

.circleci/run_tests.sh
This PR tells circleCI to ignore the directory `archived_files`. This is the directory that contains files that are not used by cBioPortal but should be present with the staging files for a study.
This will fix 
https://github.com/cBioPortal/datahub/pull/319
Tested in 
https://github.com/cBioPortal/datahub/pull/323
=> Ignore archived_files for validation

public/msk_impact_2017/data_clinical_sample.txt
Fix #316  .
- msk_impact_2017 (data_clinical_sample.txt)
- .
=> Adding changes to msk_impact_2017 study as suggested in issue #316

.circleci/config.yml, .circleci/validate_datahub_with_cbioportal.py, README.md
Implemented @jjgao 's idea from #350 . This will be checked weekly only in datahub/master.
Test result:
```
cbioportal.org contains studies which are not on cBioPortal Datahub:
cll_iuopa_2015
gbm_tcga_pub2013
hcc_msk_venturaa_2018
hnc_mskcc_2016
lusc_tcga_pub
mixed_allen_2018
sarc_mskcc
stad_tcga_pub
cBioPortal Datahub contains studies which are not on cbioportal.org:
hnc_mskcc_2014
```
=> Add CircleCI validation to validate studies on cbioportal.org with Datahub

public/brca_tcga_pub/data_clinical_patient.txt
- Replace \r line breaks with \n in clin patient brca_tcga_pub
This was causing issues with command line text readers such as Vim.
=> Replace \r line breaks with \n in clin patient brca_tcga_pub

public/brca_tcga_pub2015/data_expression_median_microRNA_removed.txt, public/brca_tcga_pub2015/data_expression_median_normals.txt
=> Removing manual Zscores for regeneration

public/brca_tcga_pub2015/data_RNA_Seq_v2_expression_median_normals.txt, public/brca_tcga_pub2015/data_RNA_Seq_v2_mRNA_median_Zscores.txt, public/brca_tcga_pub2015/data_mRNA_median_Zscores.txt, public/brca_tcga_pub2015/meta_RNA_Seq_v2_mRNA_median_Zscores.txt, public/brca_tcga_pub2015/meta_mRNA_median_Zscores.txt
=> Removed Zscores for regeneration

public/prad_broad_2013/prad_broad_2013_data_cna_hg19.seg, public/prad_broad_2013/prad_broad_2013_meta_cna_hg19_seg.txt
fixed issue https://github.com/cBioPortal/datahub/issues/314
added back seg (was marked as hg18 actually is hg19 after checking the original publication)
=> Fix prad_broad_2013 seg data

.circleci/check_changed_seed.sh, .circleci/config.yml, .circleci/install_dependencies.sh, .circleci/requirements.txt, .circleci/requirements_py, .circleci/validate_changed_seed.py, .circleci/validate_changed_studies.sh, seedDB/README.md, seedDB/Update-Seed-Database.md
This PR replaces #377 .
- Update seed database to 2.7.2.
- Print report of contents of the seed database in CircleCI.
- Add CI tests to check for common errors in the seed:
- Test if a seed database can be loaded with the latest cgds.sql (without migrating).
- Test whether the seed contains 55000 or more genes
- Test whether the seed contains 65000 or more gene aliases
- Test whether the seed contains 800 or more cancer types
- Test whether the gene symbols in the gene table are unique
- Test whether there are 0 cancer studies in the seed
- Test whether the info table is correctly set when loaded.
To test this, first a shell script checks if the seed database file is changed. If it is, docker images are pulled and python requirements are installed. Subsequently, a docker container is …
=> Update seed database to 2.7.2 and add CI tests 

.circleci/config.yml
Fix location of error reports when validating all studies
I tested this in: https://circleci.com/gh/cBioPortal/datahub/895
=> Fix location of error reports when validating all studies

public/glioma_msk_2018/data_mutations_extended.txt, public/glioma_msk_2018/data_mutations_mskcc.txt
=> Updated maf to call uncalled mutations

public/stad_tcga_pub/data_RNA_Seq_v2_mRNA_median_Zscores.txt
Fix issue #https://github.com/cBioPortal/datahub/issues/660
- stad_tcga_pub
=> stad_tcga_pub: removed extra 76 samples that were not in the publication

public/prad_p1000/data_clinical_sample.txt
Email from Josh:
Since we have exchanged emails on the P1000 dataset here I am writing because I have just found out that all the TCGA samples are now annotated as 'NA' in the sample type column when they should all be annotated as primary. 
Can you please correct this when you get a chance? https://www.cbioportal.org/study/clinicalData?id=prad_p1000
=> prad_p1000: fixed sample type for TCGA sample

.circleci/config.yml
acc_2019 validation on circleci is running for more than 30min.
=> update no_output_timeout parameter to 1hr

public/stes_tcga_pub/data_CNA.txt
=> stes_tcga_pub: added missing CNA data for 90 samples

public/prad_eururol_2017/data_clinical_patient.txt, public/prad_eururol_2017/data_mRNA_seq_fpkm.txt
Fix file format (to `Unix LF`) 
- prad_eururol_2017
=> prad_eururol_2017: Update all file format to `Unix LF`

public/coadread_mskcc/data_gene_matrix.txt, public/coadread_mskcc/meta_gene_matrix.txt
added gene matrix for coadread_mskcc
- coadread_mskcc
*assumed the samples are sequenced with panel IMPACT230 based on this line in the paper:
"We performed deep sequencing of 230 cancer-associated genes in 69 primary CRC tumors and matched metastases to define the mutational concordance of these genes in primary and metastatic tumors" and also this is an old study (2014)
=> coadread_mskcc: added gene matrix

public/histiocytosis_cobi_msk_2019/data_gene_matrix.txt, public/histiocytosis_cobi_msk_2019/meta_gene_matrix.txt
histiocytosis_cobi_msk_2019: added gene matrix
- histiocytosis_cobi_msk_2019
Unable to identify panels for samples listed below:
- (impact)
P-0004770-T03-IM5, P-0001360-T01-IM3
- (archer/raindance)
P-0008055-T03-TS1
P-0012544-T02-TS1
P-0012544-T03-TS1
P-0004770-T04-TS1
P-0015144-T02-TS1
P-0019478-T01-AH1
P-0015144-T01-AH1
- (sample ID doesn't match to any DMP ID)
P-0001219	SAMPLE-14
=> histiocytosis_cobi_msk_2019: added gene matrix

reference_data/gene_panels/data_gene_panel_bcc_unige_2016_cancer_panel.txt, reference_data/gene_panels/data_gene_panel_fmi_t5a.txt, reference_data/gene_panels/data_gene_panel_prad_mskcc_sequenom_sanger.txt
Fixes to gene panel files
- drop trailing space in stable_id
- remove description text from stable_id
- add space after colon to match style
None
=> fixes to gene panel files

public/prad_mskcc/data_mRNA_median_Zscores.txt, public/prad_mskcc/meta_mRNA_median_Zscores.txt
=> prad_mskcc: rolled back zscore data and meta files to the old method

public/ccle_broad_2019/data_drug_treatment_AUC.txt, public/ccle_broad_2019/data_drug_treatment_IC50.txt, public/ccle_broad_2019/data_drug_treatment_ZSCORE.txt, public/ccle_broad_2019/meta_drug_treatment_AUC.txt, public/ccle_broad_2019/meta_drug_treatment_IC50.txt, public/ccle_broad_2019/meta_drug_treatment_ZSCORE.txt
the third step of https://github.com/cBioPortal/cbioportal/issues/6769.
In this pull request, changed the [data format](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#generic-assay) of `TREATMENT_RESPONSE` data to fit `GENERIC_ASSAY` data format in `ccle_broad_2019` study.
=> import treatment data as generic_assay data type

public/lymphoma_cellline_msk_2020/data_clinical_sample.txt
from Younes lab: "Our cell lines are originally coming from either ATCC or DSMZ. I probably would not be able to provide ‘Sample_type’ info for all cell lines as it is not available on ATCC or DSMZ."
=> lymphoma_cellline_msk_2020: removed sample type

reference_data/gene_panels/data_gene_panel_glioma_mskcc_2019_fmi_t5.txt, reference_data/gene_panels/data_gene_panel_glioma_mskcc_2019_fmi_t7.txt
Added FoundationOneT5 and FoundationOneT7 panels for glioma_mskcc_2019 study based on the genes listed in Supplementary Table S4 of https://clincancerres.aacrjournals.org/content/25/18/5537
=> Added fmi_T5 and fmi_T7 gene panels for glioma_mskcc_2019 study

reference_data/gene_panels/data_gene_panel_guardant_73.txt
Added guardant_73 gene panel used for targeted sequencing of the cfDNA samples in breast_alpelisib_2020 study
=> breast_alpelisib_2020: Added Guardant gene panel

public/utuc_msk_2019/data_clinical_patient.txt
=> utuc_msk_2019: Added missing Age and Race category for some patients

public/brca_tcga_pub2015/data_RNA_Seq_v2_mRNA_median_Zscores.txt, public/brca_tcga_pub2015/data_mRNA_median_Zscores.txt, public/brca_tcga_pub2015/meta_RNA_Seq_v2_mRNA_median_Zscores.txt, public/brca_tcga_pub2015/meta_mRNA_median_Zscores.txt
related issue #1068 (do not want to close the card yet until the end of scrum for review of work)
=> brca_tcga_pub2015: added missing diploid zscore profiles

public/gbm_columbia_2019/data_clinical_patient.txt
Quick fix of gbm_columbia_2019 based on Ritika's comments (after the PR is merged) here: https://github.com/cBioPortal/datahub/pull/1103
=> gbm_columbia_2019: update based on ritika comments

public/ccle_broad_2019/data_fusions.txt
=> ccle_broad_2019: Added fusion file

public/crc_msk_2017/data_clinical_sample.txt, public/lgg_tcga/data_mutsig.txt
lgg_tcga: removed mutsig file
crc_msk_2017: replace MSS with MSI Status in subtype assignment
Fix https://github.com/cBioPortal/datahub/issues/506
Fix https://github.com/cBioPortal/datahub/issues/570
=> Quick fixes to lgg_tcga and crc_msk_2017

public/nepc_wcm_2016/meta_RNA_Seq_mRNA_median_Zscores.txt
=> set show_profile_in_analysis_tab to TRUE for expression profile

public/nsclc_tracerx_2017/data_mutations_extended.txt, public/nsclc_tracerx_2017/data_mutations_mskcc.txt
- update variant classification intergenic to IGR
- fix incorrect annotations from annotator (targeted region -> IGR) after manual checking
=> nsclc_tracerx_2017: more mutated fix

public/cellline_nci60/data_clinical_patient.txt
=> Attribute fix: cellline_nci60

.github/workflows/test_cbioportaldata_import_study.yml
This adds a manually run github action that can test a single study for import with cBioPortalData
=> Add github action test cBioPortalData conversion

public/blca_tcga_pub_2017/data_clinical_patient.txt, public/blca_tcga_pub_2017/data_clinical_sample.txt
Fix #1154 
- blca_tcga_pub_2017
=> blca_tcga_pub_2017: removed columns with no values

public/coad_cptac_2019/data_clinical_patient.txt, public/coad_cptac_2019/data_clinical_sample.txt
#131 
1. coad_cptac_2019
1. SEX / GENDER: The sex attribute values have been normalized to Male, Female across all studies.
=> Updated the clinical attribute gender to sex

public/blca_tcga_pub_2017/data_clinical_patient.txt, public/brca_tcga/data_bcr_clinical_data_patient.txt, public/luad_tcga/data_bcr_clinical_data_patient.txt, public/stad_tcga/data_RNA_Seq_expression_median.txt, public/stad_tcga/data_RNA_Seq_mRNA_median_all_sample_Zscores.txt
Fix #5  .
- updated the data type of clinical attributes in blca_tcga_pub_2017, brca_tcga, luad_tcga (changed DAYS_TO_DEATH, INITIAL_PATHOLOGIC_DX_YEAR, KARNOFSKY_PERFORMANCE_SCORE from STRING to NUMBER)
- data_RNA_Seq_expression_median.txt in study STAD has 68 rows where Entrez gene identifier has non-numeric values such as AC2, HP08777, MIG7. Removed the gene synonyms from Entrez column.
=> Issue #5: fix data issues reported by validator

public/lgg_ucsf_2014/data_timeline_specimen.txt
In the data_timeline_specimen.txt, sample P26_Pri_B was incorrectly
associated with sample P24, contradicting the association made
in data_clinical_sample.txt. This change switches P26_Pri_B to
being associated with P26, as it is in data_clinical_sample.txt
- lgg_ucsf_2014
=> Correct Sample Association

public/brca_jup_msk_2020/case_lists/cases_all.txt, public/brca_jup_msk_2020/case_lists/cases_sequenced.txt, public/brca_jup_msk_2020/data_clinical_sample.txt, public/brca_jup_msk_2020/data_cna_hg19.seg, public/brca_jup_msk_2020/data_mutations_extended.txt, public/brca_jup_msk_2020/data_mutations_mskcc.txt, public/brca_jup_msk_2020/meta_clinical_sample.txt, public/brca_jup_msk_2020/meta_cna_hg19_seg.txt, public/brca_jup_msk_2020/meta_mutations_extended.txt, public/brca_jup_msk_2020/meta_study.txt
=> brca_jup_msk_2020: added study

public/nbl_target_2018_pub/meta_expression_median.txt
Fix #794  .
- nbl_target_2018_pub: The stable_id of data_expression_median profile was mislabelled as miRNA zscores https://raw.githubusercontent.com/cBioPortal/datahub/master/public/nbl_target_2018_pub/meta_expression_median.txt. 
Cross checked the source and it is affymetrix gene expression data.
=> nbl_target_2018_pub: fix stable_id and datatype

public/mel_ucla_2016/meta_RNA_Seq_expression_median.txt, public/mel_ucla_2016/meta_RNA_Seq_mRNA_median_Zscores.txt, public/mel_ucla_2016/meta_RNA_Seq_mRNA_median_all_sample_Zscores.txt
Fix #1304 .
Changes made:
- The description of the RNA-Seq profile says it was FPKM but the data is read counts.
- Updated the profile name and description accordingly.
=> mel_ucla_2016: Update RNA-Seq profile name and description

public/coadread_tcga/data_methylation_hm450_normals.txt
=> Removed the duplicated columns from methylation hm450 normals

public/blca_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/brca_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/chol_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/coadread_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/esca_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/hnsc_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/kich_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/kirc_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/kirp_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/lihc_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/luad_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/lusc_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/prad_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/stad_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/thca_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt, public/ucec_tcga_pan_can_atlas_2018/meta_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt
Fix #1348 
Updated the `show_profile_in_analysis_tab` to TRUE instead of FALSE in `rna_seq_v2_mrna_median_all_sample_ref_normal_Zscores` profile.
=> Set zscores relative to normal samples profile to be shown on query page

public/brca_tcga_pan_can_atlas_2018/data_clinical_patient.txt, public/gbm_tcga/data_bcr_clinical_data_patient.txt, public/lgg_tcga/data_bcr_clinical_data_patient.txt, public/lgg_tcga_pan_can_atlas_2018/data_clinical_patient.txt
Fix #130 .
- brca_tcga_pan_can_atlas_2018
- gbm_tcga
- lgg_tcga
- lgg_tcga_pan_can_atlas_2018
Studies looked into:
brca_tcga_pan_can_atlas_2018
coadread_tcga_pan_can_atlas_2018
gbm_tcga
hnsc_tcga_pan_can_atlas_2018
kich_tcga
kirp_tcga
kirp_tcga_pan_can_atlas_2018
lgg_tcga
lgg_tcga_pan_can_atlas_2018
lihc_tcga
lihc_tcga_pan_can_atlas_2018
meso_tcga_pan_can_atlas_2018
thym_tcga
thym_tcga_pan_can_atlas_2018
ucec_tcga
ucec_tcga_pan_can_atlas_2018
=> Add missing survival months/status

public/lgg_ucsf_2014/data_timeline_treatment.txt
I noticed the dates were swapped for these two treatment intervals for P04, so fixing that.
Except it's showing up as if I updated the whole file - not sure why. All I did was swap the two treatments starting on day 488 for P04 so that the long interval is for TMZ and the short one is XRT.
=> swap dates for TMZ vs XRT for P04

public/brca_cptac_2020/data_acetylprotein_quantification.txt, public/brca_cptac_2020/data_phosphoprotein_quantification.txt
reformat GA (removed duplicate gene symbol in description/separate multiple sites with underscore
=> brca_cptac_2020 GA format clean up 

public/lung_msk_pdx/data_clinical_sample.txt
- removed slide ids
- added missing oncotree codes for 4 samples
=> lung_msk_pdx: update clinical data

public/aml_ohsu_2018/data_mutations.txt
Updated Tumor_seq_allele1 column to be same as the reference allele.
=> aml_ohsu_2018: fix tumor_seq_allele1 column

reference_data/gene_panels/data_gene_panel_ucla_1202.txt
Updated `LOC643802` to `MPHOSPH10P1` in the ucla_1202 panel
=> update outdated gene symbol in panel file

public/ccle_broad_2019/data_clinical_sample.txt
Fix #1392  .
The source [clinical data](https://depmap.org/portal/download/?release=CCLE+2019&release=Fusion&release=DNA+Copy+Number) already has mapped TCGA codes and some of the mappings seems to be not right. 
Here we have assigned the oncotree codes, cancer type and cancer type detailed based on the following clinical attributes:
1. Disease Subtype (new column added)
2. Histology
3. Lineage subtype (new column added)
4. Pathologist Annotation
Detailed mapping is here: https://docs.google.com/spreadsheets/d/1Up9gW2E1Kz9sgk10Iev2JHjaJOzDrNUMekvKuRy7MMY/edit#gid=146016842
=> Fix ccle_broad_2019 oncotree codes

reference_data/gene_panels/data_gene_panel_sarc_mskcc.txt
Sarc gene panel was broken (https://github.com/cBioPortal/datahub/issues/1662)
Fixed according to the gene panel listed in https://github.com/cBioPortal/datahub/blob/master/public/sarc_mskcc/data_gene_panel_matrix.txt
=> fix sarc gene panel for missing stable_id

public/lung_nci_2022/data_gene_panel_matrix.txt, public/lung_nci_2022/meta_gene_panel_matrix.txt
=> lung_nci_2022: add gene panel matrix file

public/msk_spectrum_tme_2022/data_resource_definition.txt, public/msk_spectrum_tme_2022/data_resource_patient.txt, public/msk_spectrum_tme_2022/data_resource_sample.txt, public/msk_spectrum_tme_2022/meta_resource_patient.txt
This is for msk_spectrum_tme_2022. Adds slides for all samples
Notes:
- some samples point to the same slide (I guess they did MSK-IMPACT + WGS on the same tissue in those cases). We don't have a good way to visualize this at the moment so I only connected them to one for now. They are easy to find (samples with same `MSK Slide ID`)
=> Add more H&E slides and one mpIF for msk_spectrum_tme_2022

public/luad_tcga_pan_can_atlas_2018/data_armlevel_cna.txt
#1818
The arm-level data was missing gains in the data file and it was fixed with the right data in the PR. This is coz of  a typo error while importing.
- luad_tcga_pan_can_atlas_2018
=> fix arm-level NA's

public/coad_silu_2022/meta_gsva_pvalues.txt
The file `meta_gsva_pvalues.txt` points to itself as datafile. Changed to point to the actual datafile. 
- coad_silu_2022
=> Fix GSVA p-value filepointer

public/coadread_tcga_pan_can_atlas_2018/data_resource_definition.txt, public/coadread_tcga_pan_can_atlas_2018/data_resource_patient.txt, public/coadread_tcga_pan_can_atlas_2018/meta_resource_definition.txt, public/coadread_tcga_pan_can_atlas_2018/meta_resource_patient.txt
Partially address https://github.com/cBioPortal/datahub/issues/2011. This adds Imaging Data Common's OHIF viewer for CT scans in TCGA COAD
Note: screenshot is out of sync (Changed the tab to say "CT Scan")
=> add IDC OHIF viewer CT scans to TCGA for READ

public/brca_metabric/data_clinical_patient.txt
The RFS data shared initially did not match the publication. The correct data was shared by the author. Compared data to publication and updated the clinical file.
=> brca_metabric: update relapse free survival data

reference_data/gene_panels/data_gene_panel_archer_heme.txt, reference_data/gene_panels/data_gene_panel_archer_solid.txt, reference_data/gene_panels/data_gene_panel_heme400.txt, reference_data/gene_panels/data_gene_panel_heme468.txt, reference_data/gene_panels/data_gene_panel_heme_hotspot.txt, reference_data/gene_panels/data_gene_panel_impact230.txt, reference_data/gene_panels/data_gene_panel_impact279.txt, reference_data/gene_panels/data_gene_panel_impact300.txt, reference_data/gene_panels/data_gene_panel_impact341.txt, reference_data/gene_panels/data_gene_panel_impact410.txt, reference_data/gene_panels/data_gene_panel_impact468.txt, reference_data/gene_panels/data_gene_panel_impact505.txt
A couple of gene symbols in the panels were outdated and have been updated to the latest symbols.
The list of symbols that were mapped to new symbols can be seen here: https://docs.google.com/spreadsheets/d/1e6pGueoR5VxldlC2t3MfgojgthQ61paCSlh7IuC8hBQ/edit#gid=0
=> MSK IMPACT/HEME/ARCHER panels - update outdated gene symbols to latest

public/luad_oncosg_2020/data_mrna_seq_v2_rsem.txt, public/luad_oncosg_2020/meta_mrna_seq_v2_rsem.txt
Based on the [user](https://groups.google.com/g/cbioportal/c/7asP7dDM7fU) issue, the RSEM data and the zscore profiles are identical. From the [data source](https://www.nature.com/articles/s41588-019-0569-6) and [OncoSG portal](https://src.gisapps.org/OncoSG_public/study/summary?id=GIS031) it is identified that the expression counts estimated from RSEM were normalized using DESeq2 v.1.16.1 followed by log transformation (adding one pseudo-count and log2 transformation) and the data appears to be zscore normalized.
=> laud_oncosg_2020: remove raw RSEM profile

.github/workflows/zip_studies.yml
The main culprit was the missing parentheses, I also double-checked my changes from #2048 and fixed some variables that I had forgotten to update. /cc @rmadupuri
=> Fix GitHub Actions spec for zip_studies

.github/workflows/zip_all_studies.yml, .github/workflows/zip_studies.yml
This fixes a regression from #2048 and ensures the GitHub Actions to zip studies will not nest them under `public/` or `crdc/gdc/` within the tarball.
cc @rmadupuri 
=> Do not nest studies inside tarballs

.circleci/config.yml, .circleci/requirements.txt, .circleci/validate_all_studies.sh
The [weekly validation test](https://app.circleci.com/pipelines/github/cBioPortal/datahub?branch=master) failed due to the validator path not being found after the switch to `cbioportal-core`.
- Fixed the validator path
- Resolved an issue with downloading the latest requests module by updating it to version 2.27.1, which CircleCI recognizes.
- Temporarily updated the cron schedule to trigger in the next 15 minutes for testing (will revert to weekly runs afterward).
=> Fix to circleci tests

public/bowel_colitis_msk_2022/data_clinical_sample.txt, public/egc_msk_tp53_ccr_2022/data_clinical_sample.txt, public/egc_mskcc_2020/data_clinical_sample.txt, public/gbc_mskcc_2022/data_clinical_sample.txt, public/lung_msk_mind_2020/data_clinical_sample.txt, public/rectal_msk_2022/data_clinical_sample.txt
Update: The germline variants were removed and hence the scores are recalculated.
bowel_colitis_msk_2022
egc_msk_tp53_ccr_2022
egc_mskcc_2020
gbc_mskcc_2022
lung_msk_mind_2020
rectal_msk_2022
=> Re-calculated TMB scores

reference_data/gene_panels/data_gene_panel_novartis_broad_1651.txt
=> Fix outdated gene symbol in novartis panel
